#!/bin/bash

dir=/home/se/ircserv
FD_MAX=1024
$BUFFER_SIZE
DEBUG_MODE="0"

clear

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[93m"
CYAN="\e[36m"
CEND="\e[0m"

nums='^[0-9]+$'
$red

echo -e 	"
 _____   _____     _____
|_   _| |  __ \   / ____|								
  | |   | |__) | | |       ___   ____   _ __  __    __
  | |   |  _  /  | |      / __| /  _ \ | '__| \ \  / / 
 _| |_  | | \ \  | |____  \__ \ \  __/ | |     \ \/ /
|_____| |_|  \_\  \_____| |___/  \___  |_|      \__/"

echo -e "
                Welcome to the ircserv 2.10 configurator! ;)
				"

echo -e "\nWhat directory do you want to install ircserv?"
echo -n "["$dir"] -> "
read red
if [[ -z "$red" ]]
then
	red=$dir
fi
if [[ -z "$red" ]]
then
	sed -i "3s|.*|\$dir|g" ./Config
else
	sed -i "3s|.*|dir=$red|g" ./Config
	dir=$red
fi

echo -e "\nHow many connections (maximum number of sockets) do you want to manage to?"
while true
do
	echo -n "["$FD_MAX"] -> "
	read red
	if [[ -z "$red" ]]
	then
		red=$FD_MAX
	elif [[ ${red:0:1} == "0" ]]
	then
		echo -e $RED"\nValue must not start with zero\n"$CEND
		continue
	elif ! [[ $red =~ $nums ]]
	then
		echo -e $RED"\nValue must be an integer\n"$CEND
		continue
	fi
	if [[ -z "$red" ]]
	then
		sed -i "4s|.*|\$FD_MAX|g" ./Config
	else
		sed -i "4s|.*|FD_MAX=$red|g" ./Config
		FD_MAX=$red
	fi
	break
done

echo -e "\nWhat buffer size do you want?"
while true
do
	echo -n "["$BUFFER_SIZE"] -> "
	read red
	if [[ -z "$red" ]]
	then
		red=$BUFFER_SIZE
	elif [[ ${red:0:1} == "0" ]]
	then
		echo -e $RED"\nValue must not start with zero\n"$CEND
		continue
	elif ! [[ $red =~ $nums ]]
	then
		echo -e $RED"\nValue must be an integer\n"$CEND
		continue
	fi
	if [[ -z "$red" ]]
	then
		sed -i "5s|.*|\$BUFFER_SIZE|g" ./Config
	else
		sed -i "5s|.*|BUFFER_SIZE=$red|g" ./Config
		BUFFER_SIZE=$red
	fi
	break
done

echo -e "\nDo you want compile with debug mdoe?"
while true
do
	if [[ $DEBUG_MODE == 0 ]] ; then
   		echo -n "Yes/No [n] -> "
	else
		echo -n "No/Yes[y] -> "
	fi
    read red
    if [[ -z "$red" ]]
    then
        red=$DEBUG_MODE
	fi
	case "$red" in
		[Yy]*)
			DEBUG_MODE="1"
			sed -i "6s|.*|DEBUG_MODE="1"|g" ./Config
			;;
		[Nn]*)
			DEBUG_MODE="0"
			sed -i "5s|.*|DEBUG_MODE="0"|g" ./Config
			;;
		*)
			echo -e $RED"\nYour reply must be 'Yes' ot 'No'\n"$CEND
			continue
			;;
	esac
    break
done
